name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Test
      run: go test -v ./...

    - name: Test with Race Detection
      run: go test -race -v ./...

    - name: Coverage
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out
        
    - name: Verify minimum coverage
      run: |
        COVERAGE=$(go test -cover ./... | grep -o '[0-9.]\+%' | sed 's/%//')
        if (( $(echo "$COVERAGE < 90" | bc -l) )); then
          echo "Test coverage is below 90%: $COVERAGE%"
          exit 1
        fi
        echo "Test coverage is acceptable: $COVERAGE%"
        
    - name: Static Analysis
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
        
    - name: Security Analysis
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...
        
    - name: Cyclomatic Complexity
      run: |
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        gocyclo -over 10 .
